openapi: "3.0.0"
info:
  title: Users Aggregation API
  version: 1.0
paths:
  /users:
    get:
      summary: List all users
      operationId: listUsers
      responses:
        '200':
          description: OK

#    post:
#      summary: Create a user
#      operationId: createPets
#  /pets/{petId}:
#    get:
#      summary: Info for a specific pet
#      operationId: showPetById

components:
  schemas:
    User:
      type: object
      required:
        - username
        - name
        - surname
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        name:
          type: string
        surname:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string